apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend
  labels:
    app: todo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/captain-yun/k8s-labs/todo-backend:v1
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "todo-db-svc"
        envFrom:
        - configMapRef:
            name: todo-db-config
        - secretRef:
            name: todo-db-secret