apiVersion: v1
kind: Pod
metadata:
  name: buggy-app-with-probe
  labels:
    app: buggy-fixed
spec:
  containers:
    - name: buggy-container
      # 중요: 실제 교육 시에는 학생들이 직접 빌드한 이미지 주소로 변경해야 합니다.
      image: captainyun/buggy-node-app:1.0 # 수업 편의를 위한 예제 이미지
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /healthz # app.js에 만든 health check 경로
          port: 8080
        initialDelaySeconds: 5 # Pod 시작 후 5초 뒤부터 검사 시작
        periodSeconds: 5 # 5초마다 검사
        failureThreshold: 1 # 1번 실패하면 바로 재시작 (의도적으로 낮게 설정하여 빠른 감지를 위함)
